version: '3'

services:
  mail_service_server:
    build: .
    depends_on:
      - mail_service_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./.env:/app/.env"

  mail_service_db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/mail_service_postgres_data:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}