version: '3'

services:
  mail_service_server:
    build: .
    depends_on:
      - mail_service_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "15000:5000"

  mail_service_db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/mail_service_postgres_data:/var/lib/postgresql/data
    ports:
      - "43211:5432"
    environment:
      - POSTGRES_USER=lucky
      - POSTGRES_PASSWORD=aslWIUT1234)!!!223@#
      - POSTGRES_DB=mail_service