version: '3'

services:
  mail_service_server:
    build: .
    depends_on:
      - mail_service_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      