package config

var LOWEST_PRIORITY_LEVEL = 0
var FREE_USER_ID = 1

var MAILING_STATUS_PENDING = 1
var MAILING_STATUS_FAILED = 2
var MAILING_STATUS_SUCCESS = 0

var PASSWORD_LENGTH_MINIMUM = 8
var REGEXP_PATTERN_ATLEAST_ONE_UPPERCASE = `[A-Z]+`
var REGEXP_PATTER_ATLEASE_ONE_SPECIAL_CHAR = `\W`

var USER_CODE_CONFIRMATION_LENGTH = 25

var LOWERCASED_APHABETICAL_CHAR = "abcdefghijklmnopqrstuvwxyz"
